CREATE DATABASE IF NOT EXISTS medease CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE medease;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(191) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  address TEXT NOT NULL,
  medicine VARCHAR(191) NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantity INT NOT NULL DEFAULT 1,
  store VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
